import { Component, OnInit } from '@angular/core';
import {MatSort, Sort} from '@angular/material/sort';
import {MatTableDataSource} from '@angular/material/table';

/**
 * @title Table with sticky columns
 */
@Component({
  selector: 'table-sticky-columns-example',
  styleUrls: ['table-sticky-columns-example.css'],
  templateUrl: 'table-sticky-columns-example.html',
})
export class TableStickyColumnsExample implements OnInit{

  autogeneratedColumn = ['january','february','march','april','may', 'june','july'];
  displayedColumns = ['exchangeName','total'];
  dataSource :MatTableDataSource<SummaryExchangeDto>;// = ELEMENT_DATA;


  constructor() {
     this.displayedColumns.splice.apply(this.displayedColumns, [1,0,...this.autogeneratedColumn]);
  }

  ngOnInit(): void {
    setTimeout(()=>{

   //this.autogeneratedColumn.splice(1, 2);
    this.dataSource = new MatTableDataSource(ELEMENT_DATA);;

  },100)
  }

  getMonthValue(months: Array<number>, i: number): number {
    console.log(i, months[i]);
    return months[i];
  }
}

export interface SummaryExchangeDto {
  exchangeActionId: number;
  exchangeName: string;
  months: number[];
  total: number;
}

const ELEMENT_DATA: SummaryExchangeDto[] = [
  {
    exchangeActionId: 14,
    exchangeName: 'Mail entrant',
    months: [23, 28, 34, 42, 31, 21, 19, 19, 42, 33, 35],
    total: 327
  },
  {
    exchangeActionId: 15,
    exchangeName: 'Mail sortant',
    months: [39, 48, 41, 47, 26, 39, 18, 17, 40, 33, 38],
    total: 386
  },
  {
    exchangeActionId: 16,
    exchangeName: 'CR RDV',
    months: [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
    total: 1
  },
];

/**  Copyright 2023 Google LLC. All Rights Reserved.
    Use of this source code is governed by an MIT-style license that
    can be found in the LICENSE file at https://angular.io/license */
